type Query {
  allUsers: [User]
  allItems: [Item]
}

type User {
  name: String!
  location: String!
  items: [Item] @relation
  email: String!
  phone: String
}

type Item {
  name: String!
  price: Float
  location: String!
  description: String!
  photo: String!
  swapped: Boolean
  date: Date!
  owner: User!
  contactByEmail: Boolean
  contactByPhone: Boolean
}
