type Account {
  email: String! @unique
  user: User! @relation
}

type Location {
  location: String
  users: [User!] @relation
}

type User {
  name: String!
  location: Location
  email: String
  items: [Item] @relation
  phone: String
  account: Account! @relation
}

type Category {
  name: String!
  items: [Item!] @relation
}

type Item {
  name: String
  price: Float
  location: String
  description: String
  photo: String
  swapped: Boolean
  date: Date
  owner: [User!] @relation
  contactByEmail: Boolean
  contactByPhone: Boolean
  category: [Category]! @relation
}

type Query {
  allUsers: [User!]
  allItems: [Item!]
  allCategories: [Category!]
  allLocations: [Location!]
  accountByEmail(email: String!): [Account!]
}

type Mutation {
  register(email: String!, password: String!): Account! @resolver
  login(email: String!, password: String!): String! @resolver
}
